### PR TITLE
Signaling

### PR DESCRIPTION
**Pull request by vagechirkov**
I think it makes sense to introduce another marker (e.g., green dot) for signaling and move the signaling decision to a separate method

image

### CODE REVIEW

**Comment by vagechirkov** [comment]
#52

**Comment by mezdahun** [comment]
I agree with separating signalling as it can happen separately from the current moving behavior. The green dot might not be well visible though. I made it more visible with a white outline in https://github.com/scioip34/ABM/pull/53/commits/41be6e52616f6e262422ed9512e54112b62db62b let me know if you'd prefer the previous version

**Comment by vagechirkov** [comment]
> I agree with separating signalling as it can happen separately from the current moving behavior. The green dot might not be well visible though. I made it more visible with a white outline in [41be6e5](https://github.com/scioip34/ABM/commit/41be6e52616f6e262422ed9512e54112b62db62b) let me know if you'd prefer the previous version

It looks way better!

**Comment by vagechirkov** [comment]
I added a simple rule for signaling: 

```python

if meter == 0:
    # no signaling if meter is zero
    return False
elif is_signaling:
    # continue signaling if meter is not zero and agent is already signaling
    return True
elif meter > signaling_cost:
    # start signaling if signaling cost is smaller than meter value
    rand_value = random.random()
    return True if rand_value < probability_of_starting_signaling else False
```

I think behavior looks quite complex and interesting! The problem is that the signaling is updated every frame, so the probability of the signaling should be pretty low to play any role. Let me know what you think! @mezdahun @DominikDeffner

signaling

**Comment by mezdahun** [comment]
IMO it looks awesome! I also think the rule for signalling makes sense but we can definitely change when needed

**Comment by DominikDeffner** [comment]
Yeah, I also really like the behavior! Almost looks a bit too efficient when I think back to how we did it haha. Do agents slow down when they detect the resource? Think that's maybe also something people would do?!

**Comment by vagechirkov** [comment]
> Yeah, I also really like the behavior! Almost looks a bit too efficient when I think back to how we did it haha. Do agents slow down when they detect the resource? Think that's maybe also something people would do?!

Agents start taxis immediately after discovering a resource. I think we can embed the slowdown factor in the taxi algorithm.

**Comment by vagechirkov** [comment]
I think we're ready to merge in general, but I'm not sure about the `probability_of_starting_signaling` parameter. @mezdahun Can we sample the `rand_value` on the other timescale (e.g., every second)?

**Comment by vagechirkov** [comment]
Now the signaling random value is updated every 100ms. I have used this https://www.pygame.org/docs/ref/time.html#pygame.time.set_timer method.

**Review by mezdahun — APPROVED** [review]

**Comment by mezdahun** [comment]
App has been moved to root, infrastructure has been change to be able to handle project specific applications. Signaling implemented.

**Comment by vagechirkov** [comment]
#54 #56

**Pull request merged**
